# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'v5mobile' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for v5mobile
    pod 'ACPAudienceBeta', '~> 1.0.2beta'
    pod 'ACPCampaignBeta', '~> 1.0.2beta'
    pod 'ACPAnalyticsBeta', '~> 1.0.2beta'
    pod 'ACPTargetBeta', '~> 1.0.2beta'
    pod 'ACPUserProfileBeta', '~> 1.0.1beta'
    pod 'ACPCoreBeta', '~> 1.0.2beta'
end
