# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'v5mobile' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for v5mobile
  #pod 'ACPTargetVEC', '~> 0.2'
    pod 'ACPCampaign', '~> 1.0'
    pod 'ACPTarget', '~> 2.0'
    pod 'ACPAnalytics', '~> 2.0'
    pod 'ACPUserProfile', '~> 2.0'
    pod 'ACPCore', '~> 2.0'
end
